### ISSUE TITLE
Neue Karte lädt falsche Ansicht im BE

### ISSUE THREAD

**Issue by wgrhstf** [Kuestenschmiede/con4gis_maps3#4]
Wenn bei einem neuen Strukturelement die Option "Als Karte verwenden" angeklickt wird, lädt zuerst die gesamte Eingabemaske im Reiter Karte. Erst nach dem speichern werden die Auswahlboxen richtig angezeigt.
![kartenstrukturen kartenstrukturelement id 100 bearbeiten - contao open source cms 3 5 2016-08-24 07-33-27](https://cloud.githubusercontent.com/assets/17173916/17919426/bf7e86da-69cd-11e6-8c8d-7065ff092f6d.png)

**Comment by coastforge-cro** [comment]
Dieses Problem ist bereits bekannt, aus unserer Sicht aber ein Problem was an contao liegt. Auch in anderen Extensions scheint dieser Fehler aufzutreten. 
Wir werden dieses Problem im Zuge einer geplanten Überarbeitung der BE-Masken noch einmal angehen.
