### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by Xendiadyon** [Kuestenschmiede/con4gis_maps3#8]
Beim Einbinden einer Karte kommt der o.g. Fehler.

jQuery ist implementiert und wird aber (SEO-bedingt) erst kurz vor Ende Body (EDIT: HTML wurde nicht angezeigt) eingebunden.
Der jQuery-Code der Karteneinbindung wird aber offenbar nicht über einen Contao-Hook eingebunden, sondern wohl fälschlicherweise im Template und wird daher aufgerufen, bevor die jquery-Datei geladen wurde.

Könnt ihr das fixen?

**Comment by coastforge-mei** [comment]
Moin Xendiadyon,

da kann ich Dir zurzeit keine Abhilfe bieten. jQuery wird in Maps 3 im Inhaltselement bzw. im Frontendmodul über die Compile-Funktion geladen (über den con4gis-Core ResourceLoader), die das Template bestückt. Im Template wird, wie in anderen Templates auch,  jQuery verwendet.

Ich habe jetzt mal im develop-Stand die _jQuery(_ aufrufe der templates in _$(_, obwohl das aus meiner Sicht keinen Unterschied machen dürfte.

Vielleicht hast Du ja noch eine Idee dazu?

Beste Grüße
Matthias

**Comment by Xendiadyon** [comment]
Mein Ansatz wäre, den jQuery-Code nicht direkt ins Template zu schreiben, sondern in die globale Variable
$GLOBALS['TL_MOOTOOLS'] (oder wie die heißt). Der Code, der dort drinnen steht, wird nämlich idR ganz unten auf der Seite ausgeführt; und dann kann man sicher sein, dass die jQuery-Library schon geladen ist (auch wenn man sie aus SEO-Sicht ans Ende vom body packt).

https://contao.ninja/API_Hook_Module.html

**Comment by JanoschOltmanns** [comment]
@Xendiadyon dieses Feature wird genau so in Kürze umgesetzt. Die ersten Umstellungen existieren bereits, wir müssen aber alle con4gis-Module berücksichtigen. Allerdings über $GLOBALS['TL_JQUERY'].
